# Generated by Django 2.2.5 on 2019-10-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191028_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='main.Branch'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'name')},
        ),
    ]
