# Generated by Django 2.2.5 on 2019-10-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191028_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='main.Material'),
            preserve_default=False,
        ),
    ]
