# Generated by Django 2.2.5 on 2019-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_invoice_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='material',
        ),
        migrations.AddField(
            model_name='invoice',
            name='material',
            field=models.ManyToManyField(related_name='invoices', to='main.Material'),
        ),
    ]
