# Generated by Django 2.2.5 on 2019-10-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_materialorder_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialorder',
            old_name='qtn',
            new_name='quantity',
        ),
    ]
