# Generated by Django 2.2.5 on 2019-11-03 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191031_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_date', models.DateField()),
                ('output_number', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoce_details', to='main.Invoice')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoce_details', to='main.Material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MaterialOrder',
        ),
    ]
