# Generated by Django 2.2.5 on 2019-11-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_invoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='total',
            field=models.DecimalField(decimal_places=2, default=21.3, max_digits=6),
            preserve_default=False,
        ),
    ]
