# Generated by Django 2.2.5 on 2019-11-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20191104_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'INACTIVE'), (3, 'Deleted')], default=1),
        ),
    ]
