# Generated by Django 2.2.5 on 2019-11-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20191106_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'فعال'), (2, 'غير فعال')], default=1, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'فعال'), (2, 'غير فعال')], default=1, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='print_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عداد الطباعة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'فعال'), (2, 'غير فعال')], default=1, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='delivery_date',
            field=models.DateField(verbose_name='تاريخ التسليم'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='output_number',
            field=models.PositiveIntegerField(verbose_name='رقم الاخراج'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='الاجمالي'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=30, verbose_name='اسم المادة'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'فعال'), (2, 'غير فعال')], default=1, verbose_name='الحالة'),
        ),
    ]
