# Generated by Django 2.2.5 on 2019-11-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191106_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, verbose_name='الاجمالي'),
        ),
    ]
