# Generated by Django 2.2.5 on 2019-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20191113_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='folder_path',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='company',
            name='folder_path',
            field=models.CharField(max_length=400),
        ),
    ]
