# Generated by Django 2.2.5 on 2019-11-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_company_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=70, verbose_name='اسم المادة'),
        ),
    ]
